language: go

sudo: required
dist: trusty

services:
  - docker

go:
  - 1.6

env:
  - ORIENT_VERS=2.1.5

matrix:
  include:
    - go: 1.6
      env: ORIENT_VERS=2.1.2
    - go: 1.6
      env: ORIENT_VERS=2.0

install:
  - mkdir -p $GOPATH/src/github.com/qichaoch
  - mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/qichaoch/orientgo
  - export TRAVIS_BUILD_DIR=$GOPATH/src/github.com/qichaoch/orientgo
  - cd $GOPATH/src/github.com/qichaoch/orientgo
  - docker pull dennwc/orientdb:${ORIENT_VERS}
#  - go get golang.org/x/tools/cmd/cover
#  - go get github.com/golang/lint/golint
  - go get -t -v ./...

script:
  - go test -v -race ./...
  - go vet .
  - go vet ./obinary
  - go tool vet -methods=false ./obinary/rw
#  - go test -covermode=atomic ./...
#  - $HOME/gopath/bin/golint .
